"""Deterministic project file inventory and language detection without model calls."""

from __future__ import annotations

import json
import re
import sqlite3
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import PurePosixPath
from typing import Sequence


SUPPORTED_ANALYSIS_LANGUAGES = frozenset(
    {
        "c",
        "cpp",
        "csharp",
        "html",
        "javascript",
        "pascal",
        "powershell",
        "python",
        "rust",
        "shell",
        "sql",
        "typescript",
    }
)

STRONG_EXTENSIONS: dict[str, tuple[str, str]] = {
    ".py": ("python", "source"),
    ".pyw": ("python", "source"),
    ".pyi": ("python", "source"),
    ".pas": ("pascal", "source"),
    ".pp": ("pascal", "source"),
    ".dpr": ("pascal", "source"),
    ".lpr": ("pascal", "source"),
    ".cs": ("csharp", "source"),
    ".cpp": ("cpp", "source"),
    ".cxx": ("cpp", "source"),
    ".cc": ("cpp", "source"),
    ".hpp": ("cpp", "source"),
    ".hxx": ("cpp", "source"),
    ".hh": ("cpp", "source"),
    ".inl": ("cpp", "source"),
    ".tpp": ("cpp", "source"),
    ".c": ("c", "source"),
    ".rs": ("rust", "source"),
    ".js": ("javascript", "source"),
    ".mjs": ("javascript", "source"),
    ".cjs": ("javascript", "source"),
    ".jsx": ("javascript", "source"),
    ".ts": ("typescript", "source"),
    ".mts": ("typescript", "source"),
    ".cts": ("typescript", "source"),
    ".tsx": ("typescript", "source"),
    ".html": ("html", "markup"),
    ".htm": ("html", "markup"),
    ".xhtml": ("html", "markup"),
    ".sql": ("sql", "query"),
    ".psql": ("sql", "query"),
    ".sh": ("shell", "script"),
    ".bash": ("shell", "script"),
    ".zsh": ("shell", "script"),
    ".ksh": ("shell", "script"),
    ".ps1": ("powershell", "script"),
}

ANCILLARY_EXTENSIONS: dict[str, tuple[str, str]] = {
    ".css": ("css", "stylesheet"),
    ".scss": ("scss", "stylesheet"),
    ".sass": ("sass", "stylesheet"),
    ".less": ("less", "stylesheet"),
    ".json": ("json", "data"),
    ".jsonl": ("json", "data"),
    ".yaml": ("yaml", "config"),
    ".yml": ("yaml", "config"),
    ".toml": ("toml", "config"),
    ".xml": ("xml", "data"),
    ".md": ("markdown", "documentation"),
    ".rst": ("restructuredtext", "documentation"),
    ".txt": ("text", "documentation"),
    ".csv": ("csv", "data"),
    ".tsv": ("tsv", "data"),
    ".ini": ("ini", "config"),
    ".cfg": ("ini", "config"),
    ".conf": ("config", "config"),
    ".properties": ("properties", "config"),
    ".lock": ("lockfile", "data"),
    ".svg": ("svg", "markup"),
    ".dfm": ("pascal-form", "resource"),
    ".res": ("resource", "resource"),
}

SPECIAL_FILENAMES: dict[str, tuple[str, str]] = {
    "dockerfile": ("dockerfile", "config"),
    "makefile": ("make", "config"),
    "gnumakefile": ("make", "config"),
    "cmakelists.txt": ("cmake", "config"),
    "meson.build": ("meson", "config"),
    "rakefile": ("ruby", "script"),
    "gemfile": ("ruby", "config"),
    ".bashrc": ("shell", "script"),
    ".bash_profile": ("shell", "script"),
    ".profile": ("shell", "script"),
    ".zshrc": ("shell", "script"),
}

MANIFEST_SUFFIX_HINTS: tuple[tuple[str, str], ...] = (
    (".csproj", "csharp"),
    (".sln", "csharp"),
    (".fsproj", "fsharp"),
    (".dproj", "pascal"),
    (".groupproj", "pascal"),
    (".xcodeproj", "cpp"),
)

MANIFEST_NAME_HINTS: dict[str, str] = {
    "cargo.toml": "rust",
    "cargo.lock": "rust",
    "pyproject.toml": "python",
    "setup.py": "python",
    "setup.cfg": "python",
    "requirements.txt": "python",
    "pipfile": "python",
    "package.json": "javascript",
    "package-lock.json": "javascript",
    "yarn.lock": "javascript",
    "pnpm-lock.yaml": "javascript",
    "cmakelists.txt": "cpp",
}

GENERATED_PATH_PATTERNS = (
    re.compile(r"(?i)(?:^|/)(?:generated|autogenerated|gen)(?:/|$)"),
    re.compile(r"(?i)(?:\.min\.js|\.g\.cs|\.designer\.cs|_pb2\.py|\.generated\.[^.]+)$"),
)
GENERATED_TEXT_PATTERN = re.compile(
    r"(?i)(?:<auto-generated|automatically generated|generated by (?:the )?[\w .+-]+)"
)


@dataclass(frozen=True)
class InventorySourceFile:
    path: str
    content: bytes


@dataclass(frozen=True)
class FileInventory:
    path: str
    file_kind: str
    language: str | None
    language_confidence: float
    detection_method: str
    encoding: str | None
    line_count: int | None
    is_binary: bool
    is_generated: bool
    is_entrypoint_candidate: bool
    analysis_eligible: bool


@dataclass(frozen=True)
class ProjectLanguage:
    language: str
    file_count: int
    source_bytes: int
    confidence: float
    is_primary: bool


@dataclass(frozen=True)
class ProjectInventory:
    files: tuple[FileInventory, ...]
    languages: tuple[ProjectLanguage, ...]
    primary_language: str | None


def decode_text_content(content: bytes) -> tuple[str | None, str | None]:
    """Decode common source encodings while rejecting control-heavy binary data."""
    candidates: list[tuple[str, str]] = []
    if content.startswith(b"\xef\xbb\xbf"):
        candidates.append(("utf-8-sig", "utf-8-sig"))
    elif content.startswith((b"\xff\xfe", b"\xfe\xff")):
        candidates.append(("utf-16", "utf-16"))
    else:
        candidates.append(("utf-8", "utf-8"))
        if b"\0" not in content[:8192]:
            candidates.append(("cp1252", "windows-1252"))
    for codec, display_name in candidates:
        try:
            text = content.decode(codec)
        except (UnicodeDecodeError, LookupError):
            continue
        if not text:
            return text, display_name
        control_count = sum(
            ord(character) < 32 and character not in "\t\r\n\f"
            for character in text[:8192]
        )
        if control_count / min(len(text), 8192) <= 0.01:
            return text, display_name
    return None, None


def extension_for(path: str) -> str:
    return PurePosixPath(path).suffix.casefold()


def manifest_hints(files: Sequence[InventorySourceFile]) -> Counter[str]:
    hints: Counter[str] = Counter()
    for source in files:
        path = PurePosixPath(source.path)
        name = path.name.casefold()
        hinted = MANIFEST_NAME_HINTS.get(name)
        if hinted:
            hints[hinted] += 4
        for suffix, language in MANIFEST_SUFFIX_HINTS:
            if name.endswith(suffix):
                hints[language] += 4
        if name == "package.json":
            text, _encoding = decode_text_content(source.content)
            if text:
                try:
                    package = json.loads(text)
                except json.JSONDecodeError:
                    package = None
                if isinstance(package, dict):
                    dependency_names: set[str] = set()
                    for key in ("dependencies", "devDependencies", "peerDependencies"):
                        values = package.get(key)
                        if isinstance(values, dict):
                            dependency_names.update(str(value).casefold() for value in values)
                    if "typescript" in dependency_names or any(
                        str(value).casefold().endswith(('.ts', '.tsx'))
                        for value in package.values()
                        if isinstance(value, str)
                    ):
                        hints["typescript"] += 6
        if name == "cmakelists.txt":
            text, _encoding = decode_text_content(source.content)
            if text and re.search(r"(?i)\b(?:CXX|C\+\+)\b|\.c(?:pp|xx)\b", text):
                hints["cpp"] += 4
            if text and re.search(r"(?i)\bLANGUAGES\s+C(?:\s|\))", text):
                hints["c"] += 2
    return hints


def project_extension_context(files: Sequence[InventorySourceFile]) -> Counter[str]:
    context: Counter[str] = Counter()
    for source in files:
        known = STRONG_EXTENSIONS.get(extension_for(source.path))
        if known:
            context[known[0]] += max(1, len(source.content))
    return context


def shebang_language(text: str) -> str | None:
    first_line = text.splitlines()[0] if text.splitlines() else ""
    if not first_line.startswith("#!"):
        return None
    command = first_line.casefold()
    if re.search(r"\bpython(?:[0-9.]*)?\b", command):
        return "python"
    if re.search(r"\b(?:ba|z|k)?sh\b|\bdash\b", command):
        return "shell"
    if re.search(r"\b(?:node|deno|bun)\b", command):
        return "javascript"
    if re.search(r"\b(?:pwsh|powershell)\b", command):
        return "powershell"
    return None


def language_from_content(text: str) -> tuple[str | None, float]:
    sample = text[:16_000]
    stripped = sample.lstrip()
    if re.match(r"(?is)<!doctype\s+html\b|<html(?:\s|>)", stripped):
        return "html", 0.95
    if re.search(r"(?im)^\s*(?:program|unit|library)\s+[A-Za-z_]\w*\s*;", sample):
        return "pascal", 0.9
    if re.search(r"(?m)^\s*(?:use\s+[A-Za-z_:]+\s*;|impl(?:<[^>]+>)?\s+\w+|(?:pub\s+)?fn\s+\w+\s*\()", sample):
        return "rust", 0.82
    if re.search(r"(?m)^\s*(?:using\s+System(?:\.|;)|namespace\s+[\w.]+\s*[;{])", sample):
        return "csharp", 0.82
    if re.search(r"(?m)^\s*#\s*include\s*<(?:iostream|vector|string|memory)>|\bstd::", sample):
        return "cpp", 0.82
    if re.search(r"(?im)^\s*(?:select|insert\s+into|update\s+\w+\s+set|create\s+(?:table|view|procedure|function))\b", sample):
        return "sql", 0.78
    if re.search(r"(?m)^\s*(?:(?:export\s+)?(?:interface\s+\w+\s*[{<]|type\s+\w+\s*=)|(?:export\s+)?function\s+\w+\s*\([^\n)]*:\s*\w+)", sample):
        return "typescript", 0.82
    if re.search(r"(?im)^\s*(?:function\s+[A-Za-z]+-[A-Za-z]+\s*[{(]|\[CmdletBinding\s*\(|param\s*\(\s*\[)", sample):
        return "powershell", 0.82
    if re.search(r"(?m)^\s*[A-Za-z_]\w*\s*\(\s*\)\s*\{", sample):
        return "shell", 0.7
    if re.search(r"(?m)^\s*(?:export\s+|import\s+.+\s+from\s+|(?:const|let|var)\s+\w+\s*=|function\s+\w+\s*\()", sample):
        return "javascript", 0.7
    if re.search(r"(?m)^\s*(?:from\s+[\w.]+\s+import\s+|import\s+[\w.]+\s*$|(?:async\s+)?def\s+\w+\s*\()", sample):
        return "python", 0.72
    return None, 0.0


def resolve_ambiguous_extension(
    extension: str,
    context: Counter[str],
    hints: Counter[str],
) -> tuple[str | None, float, str]:
    if extension == ".h":
        cpp_score = context["cpp"] + hints["cpp"] * 10_000
        c_score = context["c"] + hints["c"] * 10_000
        if cpp_score > c_score:
            return "cpp", 0.88, "project_context"
        if c_score > cpp_score:
            return "c", 0.88, "project_context"
        return "cpp", 0.55, "ambiguous_extension"
    if extension == ".inc":
        pascal_score = context["pascal"] + hints["pascal"] * 10_000
        c_family_score = context["cpp"] + context["c"] + hints["cpp"] * 10_000
        if pascal_score > c_family_score:
            return "pascal", 0.82, "project_context"
        if c_family_score:
            return ("cpp" if context["cpp"] >= context["c"] else "c"), 0.72, "project_context"
    return None, 0.0, "unknown"


def file_is_generated(path: str, text: str | None) -> bool:
    if any(pattern.search(path) for pattern in GENERATED_PATH_PATTERNS):
        return True
    return bool(text and GENERATED_TEXT_PATTERN.search(text[:2_000]))


def is_entrypoint_candidate(path: str, language: str | None, text: str | None) -> bool:
    if not language or text is None:
        return False
    stem = PurePosixPath(path).stem.casefold()
    name = PurePosixPath(path).name.casefold()
    if language == "python":
        return stem in {"main", "app", "manage", "cli"} or bool(
            re.search(r"(?m)^\s*if\s+__name__\s*==\s*['\"]__main__['\"]\s*:", text)
        )
    if language in {"c", "cpp", "csharp", "rust"}:
        return stem in {"main", "program", "app"} or bool(
            re.search(r"(?m)\b(?:fn\s+main|(?:int|void|static\s+void)\s+[Mm]ain)\s*\(", text)
        )
    if language == "pascal":
        return bool(re.search(r"(?im)^\s*program\s+[A-Za-z_]\w*\s*;", text))
    if language in {"javascript", "typescript"}:
        return stem in {"main", "index", "app", "server", "cli"}
    if language == "html":
        return name in {"index.html", "index.htm"}
    if language in {"shell", "powershell"}:
        return stem in {"main", "run", "start", "entrypoint", "install"}
    return False


def inventory_file(
    source: InventorySourceFile,
    context: Counter[str],
    hints: Counter[str],
) -> FileInventory:
    text, encoding = decode_text_content(source.content)
    if text is None:
        return FileInventory(
            path=source.path,
            file_kind="binary",
            language=None,
            language_confidence=1.0,
            detection_method="binary_content",
            encoding=None,
            line_count=None,
            is_binary=True,
            is_generated=False,
            is_entrypoint_candidate=False,
            analysis_eligible=False,
        )

    path = PurePosixPath(source.path)
    name = path.name.casefold()
    extension = path.suffix.casefold()
    language: str | None = None
    file_kind = "unknown"
    confidence = 0.0
    method = "unknown"
    if name in SPECIAL_FILENAMES:
        language, file_kind = SPECIAL_FILENAMES[name]
        confidence, method = 0.99, "filename"
    elif extension in STRONG_EXTENSIONS:
        language, file_kind = STRONG_EXTENSIONS[extension]
        confidence, method = 0.99, "extension"
    elif extension in {".h", ".inc"}:
        language, confidence, method = resolve_ambiguous_extension(extension, context, hints)
        file_kind = "source" if language else "unknown"
    elif extension in ANCILLARY_EXTENSIONS:
        language, file_kind = ANCILLARY_EXTENSIONS[extension]
        confidence, method = 0.98, "extension"
    else:
        language = shebang_language(text)
        if language:
            file_kind, confidence, method = "script", 0.96, "shebang"
        else:
            language, confidence = language_from_content(text)
            if language:
                file_kind = "markup" if language == "html" else "query" if language == "sql" else "source"
                method = "content_signature"

    generated = file_is_generated(source.path, text)
    eligible = bool(language in SUPPORTED_ANALYSIS_LANGUAGES and not generated)
    return FileInventory(
        path=source.path,
        file_kind=file_kind,
        language=language,
        language_confidence=confidence,
        detection_method=method,
        encoding=encoding,
        line_count=text.count("\n") + 1 if text else 0,
        is_binary=False,
        is_generated=generated,
        is_entrypoint_candidate=is_entrypoint_candidate(source.path, language, text),
        analysis_eligible=eligible,
    )


def build_project_inventory(files: Sequence[InventorySourceFile]) -> ProjectInventory:
    context = project_extension_context(files)
    hints = manifest_hints(files)
    inventories = tuple(inventory_file(source, context, hints) for source in files)
    file_sizes = {source.path: len(source.content) for source in files}
    counts: Counter[str] = Counter()
    sizes: Counter[str] = Counter()
    confidence_totals: defaultdict[str, float] = defaultdict(float)
    scores: Counter[str] = Counter()
    for item in inventories:
        if not item.language or item.language not in SUPPORTED_ANALYSIS_LANGUAGES:
            continue
        size = file_sizes[item.path]
        counts[item.language] += 1
        sizes[item.language] += size
        confidence_totals[item.language] += item.language_confidence
        scores[item.language] += (
            max(1, size) + 1_024
            if item.analysis_eligible
            else max(1, size // 10) + 128
        )
    for language, weight in hints.items():
        if counts[language]:
            scores[language] += weight * 10_000
    primary = None
    if scores:
        primary = sorted(scores, key=lambda language: (-scores[language], language))[0]
    languages = tuple(
        ProjectLanguage(
            language=language,
            file_count=counts[language],
            source_bytes=sizes[language],
            confidence=(confidence_totals[language] / counts[language]) if counts[language] else 0.0,
            is_primary=language == primary,
        )
        for language in sorted(counts, key=lambda language: (-scores[language], language))
    )
    return ProjectInventory(inventories, languages, primary)


def inventory_project_database(db: sqlite3.Connection, project_id: str) -> ProjectInventory:
    rows = db.execute(
        "SELECT path, content FROM project_files WHERE project_id = ? ORDER BY path",
        (project_id,),
    ).fetchall()
    if not rows:
        raise ValueError("The project does not contain stored files")
    inventory = build_project_inventory(
        [InventorySourceFile(str(row["path"]), bytes(row["content"])) for row in rows]
    )
    by_path = {item.path: item for item in inventory.files}
    db.executemany(
        """
        UPDATE project_files
        SET file_kind = ?, language = ?, language_confidence = ?,
            detection_method = ?, encoding = ?, line_count = ?, is_binary = ?,
            is_generated = ?, is_entrypoint_candidate = ?, analysis_eligible = ?
        WHERE project_id = ? AND path = ?
        """,
        (
            (
                item.file_kind,
                item.language,
                item.language_confidence,
                item.detection_method,
                item.encoding,
                item.line_count,
                int(item.is_binary),
                int(item.is_generated),
                int(item.is_entrypoint_candidate),
                int(item.analysis_eligible),
                project_id,
                item.path,
            )
            for item in by_path.values()
        ),
    )
    db.execute("DELETE FROM project_languages WHERE project_id = ?", (project_id,))
    db.executemany(
        """
        INSERT INTO project_languages(
            project_id, language, file_count, source_bytes, confidence, is_primary
        ) VALUES (?, ?, ?, ?, ?, ?)
        """,
        (
            (
                project_id,
                language.language,
                language.file_count,
                language.source_bytes,
                language.confidence,
                int(language.is_primary),
            )
            for language in inventory.languages
        ),
    )
    language_json = json.dumps(
        [
            {
                "language": language.language,
                "file_count": language.file_count,
                "source_bytes": language.source_bytes,
                "confidence": round(language.confidence, 4),
                "is_primary": language.is_primary,
            }
            for language in inventory.languages
        ],
        separators=(",", ":"),
    )
    db.execute(
        """
        UPDATE projects
        SET primary_language = ?, languages_json = ?, inventory_status = 'completed',
            inventory_error = NULL, updated_at = CURRENT_TIMESTAMP
        WHERE id = ?
        """,
        (inventory.primary_language, language_json, project_id),
    )
    return inventory
