from __future__ import annotations

import hashlib

import main
from project_inventory import InventorySourceFile, build_project_inventory
from tests.helpers import DatabaseTestCase


def source(path: str, content: str | bytes) -> InventorySourceFile:
    encoded = content.encode() if isinstance(content, str) else content
    return InventorySourceFile(path, encoded)


class DeterministicLanguageDetectionTests(DatabaseTestCase):
    def test_requested_languages_are_detected_from_extensions(self) -> None:
        inventory = build_project_inventory(
            [
                source("src/app.py", "def main():\n    pass\n"),
                source("src/program.pas", "program Demo; begin end."),
                source("src/Program.cs", "using System; class Program {}"),
                source("src/main.cpp", "int main() { return 0; }"),
                source("src/lib.rs", "pub fn value() -> i32 { 1 }"),
                source("web/app.js", "export function app() {}"),
                source("web/index.html", "<!doctype html><html></html>"),
                source("db/schema.sql", "create table demo(id integer);"),
                source("scripts/run.sh", "#!/bin/sh\necho ready\n"),
            ]
        )
        detected = {item.path: item.language for item in inventory.files}
        self.assertEqual(
            detected,
            {
                "src/app.py": "python",
                "src/program.pas": "pascal",
                "src/Program.cs": "csharp",
                "src/main.cpp": "cpp",
                "src/lib.rs": "rust",
                "web/app.js": "javascript",
                "web/index.html": "html",
                "db/schema.sql": "sql",
                "scripts/run.sh": "shell",
            },
        )
        self.assertTrue(all(item.detection_method == "extension" for item in inventory.files))
        self.assertTrue(all(item.analysis_eligible for item in inventory.files))

    def test_shebang_content_encoding_generated_and_binary_classification(self) -> None:
        utf16_pascal = "program Wide;\r\nbegin\r\nend.\r\n".encode("utf-16")
        inventory = build_project_inventory(
            [
                source("tools/deploy", "#!/usr/bin/env bash\necho deploy\n"),
                source("unknown/source.code", "using System;\nnamespace Demo {}\n"),
                source("legacy/wide.pas", utf16_pascal),
                source("web/app.min.js", "// generated by bundler\nconst value=1;"),
                source("assets/image.dat", b"\x00\x01\x02\xff"),
            ]
        )
        by_path = {item.path: item for item in inventory.files}
        self.assertEqual(by_path["tools/deploy"].language, "shell")
        self.assertEqual(by_path["tools/deploy"].detection_method, "shebang")
        self.assertEqual(by_path["unknown/source.code"].language, "csharp")
        self.assertEqual(by_path["unknown/source.code"].detection_method, "content_signature")
        self.assertEqual(by_path["legacy/wide.pas"].encoding, "utf-16")
        self.assertEqual(by_path["legacy/wide.pas"].line_count, 4)
        self.assertTrue(by_path["web/app.min.js"].is_generated)
        self.assertFalse(by_path["web/app.min.js"].analysis_eligible)
        self.assertTrue(by_path["assets/image.dat"].is_binary)
        self.assertIsNone(by_path["assets/image.dat"].language)

    def test_extensionless_content_signature_is_classified_but_not_analyzed(self) -> None:
        inventory = build_project_inventory(
            [
                source("notes/python notes", "def example():\n    return 1\n"),
                source("tools/deploy", "#!/usr/bin/env python\nprint('ready')\n"),
            ]
        )
        by_path = {item.path: item for item in inventory.files}

        self.assertEqual(by_path["notes/python notes"].language, "python")
        self.assertEqual(
            by_path["notes/python notes"].detection_method,
            "content_signature",
        )
        self.assertFalse(by_path["notes/python notes"].analysis_eligible)
        self.assertEqual(by_path["tools/deploy"].detection_method, "shebang")
        self.assertTrue(by_path["tools/deploy"].analysis_eligible)

    def test_ambiguous_headers_and_includes_use_project_context(self) -> None:
        cpp = build_project_inventory(
            [
                source("CMakeLists.txt", "project(Demo LANGUAGES CXX)"),
                source("src/main.cpp", "#include \"value.h\"\nint main() {}"),
                source("src/value.h", "int value();"),
            ]
        )
        cpp_header = next(item for item in cpp.files if item.path.endswith("value.h"))
        self.assertEqual(cpp_header.language, "cpp")
        self.assertEqual(cpp_header.detection_method, "project_context")

        pascal = build_project_inventory(
            [
                source("src/main.pas", "program Demo; {$I constants.inc} begin end."),
                source("src/constants.inc", "const Answer = 42;"),
            ]
        )
        include = next(item for item in pascal.files if item.path.endswith(".inc"))
        self.assertEqual(include.language, "pascal")
        self.assertEqual(include.detection_method, "project_context")

    def test_manifest_context_selects_primary_language_in_mixed_project(self) -> None:
        inventory = build_project_inventory(
            [
                source("Cargo.toml", "[package]\nname='demo'\n"),
                source("src/main.rs", "fn main() {}"),
                source("web/large.js", "const value = 1;\n" * 2_000),
                source("web/index.html", "<!doctype html><html></html>"),
            ]
        )
        self.assertEqual(inventory.primary_language, "rust")
        summaries = {item.language: item for item in inventory.languages}
        self.assertEqual(set(summaries), {"rust", "javascript", "html"})
        self.assertTrue(summaries["rust"].is_primary)
        self.assertEqual(summaries["javascript"].file_count, 1)


class ProjectInventoryPersistenceTests(DatabaseTestCase):
    def test_startup_backfills_pending_uploaded_projects(self) -> None:
        user_id = self.create_user("inventory-backfill")
        content = b"if __name__ == '__main__':\n    print('ready')\n"
        with main.connect_db() as db:
            db.execute(
                "INSERT INTO chat_histories(id, user_id, title) VALUES ('inventory-chat', ?, 'Inventory')",
                (user_id,),
            )
            db.execute(
                """
                INSERT INTO projects(
                    id, user_id, chat_id, name, source_kind, file_count, total_bytes
                ) VALUES ('pending-project', ?, 'inventory-chat', 'demo', 'folder', 1, ?)
                """,
                (user_id, len(content)),
            )
            db.execute(
                """
                INSERT INTO project_files(
                    project_id, path, content, size_bytes, sha256, is_binary
                ) VALUES ('pending-project', 'demo/main.py', ?, ?, ?, 0)
                """,
                (content, len(content), hashlib.sha256(content).hexdigest()),
            )

        main.initialise_db()

        with main.connect_db() as db:
            project = db.execute(
                """
                SELECT primary_language, inventory_status, parser_status,
                       parser_parsed_file_count, structure_status, definition_count,
                       function_analysis_status, function_analysis_total_count
                FROM projects WHERE id = 'pending-project'
                """
            ).fetchone()
            file_row = db.execute(
                """
                SELECT language, detection_method, line_count,
                       is_entrypoint_candidate, analysis_eligible
                FROM project_files WHERE project_id = 'pending-project'
                """
            ).fetchone()
            languages = db.execute(
                "SELECT language, is_primary FROM project_languages WHERE project_id = 'pending-project'"
            ).fetchall()
        self.assertEqual(
            tuple(project),
            ("python", "completed", "completed", 1, "completed", 0, "completed", 0),
        )
        self.assertEqual(tuple(file_row), ("python", "extension", 3, 1, 1))
        self.assertEqual([tuple(row) for row in languages], [("python", 1)])


if __name__ == "__main__":
    import unittest

    unittest.main()
